workflows:
  android-capacitor:
    name: Android Release Build
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
