workflows:
  android-capacitor:
    name: Android Build
    instance_type: linux

    environment:
      node: 20
      java: 17
      vars:
        GRADLE_OPTS: "-Xmx4g"

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync android

      - name: Fix gradlew permissions
        script: chmod +x android/gradlew

      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
