workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.jesusquizbatler33.app"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync android

      - name: Build Web App
        script: |
          npm run build

      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
