workflows:
  android-capacitor:
    name: Android Release Build
    machine:
      os: linux
    environment:
      java: 17
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Fix gradlew permissions
        script: chmod +x android/gradlew
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab