workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.jesusquiz.battle33"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync android

      - name: Build Web App
        script: |
          npm run build

      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
gradle:
  arguments: "--no-daemon --stacktrace --info"
instance_type: mac_mini_m2
env:
  ANDROID_SDK_VERSION: 35

